export default {
  SET_INPUT_REGISTER_FIRSTNAME: 'SET_INPUT_REGISTER_FIRSTNAME',
  SET_INPUT_REGISTER_LASTNAME: 'SET_INPUT_REGISTER_LASTNAME',
  SET_INPUT_REGISTER_EMAIL: 'SET_INPUT_REGISTER_EMAIL',
  SET_INPUT_REGISTER_PASSWORD1: 'SET_INPUT_REGISTER_PASSWORD1',
  SET_INPUT_REGISTER_PASSWORD2: 'SET_INPUT_REGISTER_PASSWORD2',
  RESET_INPUT_REGISTER: 'RESET_INPUT_REGISTER',
  SET_INPUT_LOGIN_EMAIL: 'SET_INPUT_LOGIN_EMAIL',
  SET_INPUT_LOGIN_PASSWORD: 'SET_INPUT_LOGIN_PASSWORD',
  RESET_INPUT_LOGIN: 'RESET_INPUT_LOGIN',
}
